### PR TITLE
 add Vietnamese translation

### PR DESCRIPTION
**Pull request by TuanTQ15**
- [x] I created a new folder `i18n/vi` for my translated files
- [x] I translated `metadata.yml` file
- [x] I translated `white-paper.md` file
- [x] Tag @teaxyz to enable CI (if not run by default)
- [x] Ensure all CI checks pass
- [ ] Review CI-generated PDF artifact to ensure correct generation

### CODE REVIEW

**Comment by TuanTQ15** [comment]
@mxcl Hi sir, can you check dependencies? I think v 1.0.5 have some issues. I try run make and I got the same issue from CI/compile.
```
"Error producing PDF.
! LaTeX Error: File `ctexhook.sty' not found."
```

**Comment by TuanTQ15** [comment]
Any support ?

**Comment by jhheider** [comment]
[this](https://wiki.archlinux.org/title/TeX_Live/CJK#ctexhook.sty_not_found) suggests that adding `texlive-lang-chinese` will install the required hook. I'll add it to your branch and see if that solves it.

**Comment by mxcl** [comment]
Sorry, I missed this ping. Did the issue get resolved?

**Comment by TuanTQ15** [comment]
Hi sir, I will check it tmr. 1:16 A.M at my timezone, I going to sleep because I need to work tmr. Thank you

**Comment by TuanTQ15** [comment]
> Sorry, I missed this ping. Did the issue get resolved?

Hi sir, I will check it tmr. 1:16 A.M at my timezone, I going to sleep because I need to work tmr. Thank you

**Comment by TuanTQ15** [comment]
> Sorry, I missed this ping. Did the issue get resolved?

It good for me.

**Pull request closed without merging**
