### PR TITLE
docs: use "proof-of-stake" consistently

### PR DESCRIPTION
**Pull request by artburkart**
There are 6 occurrences of "proof-of-stake" in the document. Before this edit, half of them were spelled "proof of stake".

### CODE REVIEW

**Review by mxcl — APPROVED** [review]
Approved provided this is the preference of TB

**Comment by mxcl** [comment]
It was marked as draft, we'll merge if it’s ready. @artburkart

**Comment by artburkart** [comment]
Sounds good! 👍 

I created it as a draft because I wanted to see what was necessary to build the PDF.
I'm trying to build the PDF locally on Ubuntu (on Windows), but I'm having difficulty with the setup instructions. I can't find a tap for livetex, and so far, I'm getting this error:

```
artburkart@LAPTOP-I0C5AIMF:/mnt/d/Code/white-paper$ make
pandoc \
--number-sections \
--output tea.white-paper.pdf \
--metadata-file metadata.yml \
--filter pandoc-crossref \
--csl=tea.csl \
--citeproc \
white-paper.md
Unknown option --citeproc.
Try pandoc --help for more information.
make: *** [Makefile:4: tea.white-paper.pdf] Error 2
```

This was the first repository I found for livetex: https://github.com/questbeat/LiveTeX

In any case, I'll make PRs that follow all of @thomas-borrel's guidance. 👍 Thanks again!

**Comment by mxcl** [comment]
@Xercesblu3 how did you get it working on Windows?

**Comment by Xercesblu3** [comment]
Weird. The same way (I assume you used WSL to load Ubuntu @artburkart) accept I had to substitute livetex for basictex, since basictex didn't seem to exist in the environment for some reason. I then updated the instructions. Let me see if I can scrap what I have and start over to verify this is correct. Some of this is still new to me.

**Comment by artburkart** [comment]
`brew search` didn't find a "basictex" or a "livetex" tap.

```
$ brew search basictex
==> Formulae
basex

$ brew search livetex
==> Formulae
livestreamer
```

**Comment by artburkart** [comment]
Oh, I think it's supposed to be "texlive".

**Comment by artburkart** [comment]
Installing dependencies on WSL is super slow. 😅 I'll let you know once I finally have the thing installed and can test it.

**Comment by artburkart** [comment]
Okay, I got all the dependencies installed successfully, but I think there's something weird about the `--citeproc` option.
I'm still getting this:

```
$ make
pandoc \
--number-sections \
--output tea.white-paper.pdf \
--metadata-file metadata.yml \
--filter pandoc-crossref \
--csl=tea.csl \
--citeproc \
white-paper.md
Unknown option --citeproc.
Try pandoc --help for more information.
make: *** [Makefile:4: tea.white-paper.pdf] Error 2
```

I think I need to figure out how to enable the `citeproc` thing.

**Comment by jhheider** [comment]
> I think I need to figure out how to enable the `citeproc` thing.

In linux (from our GitHub action):
```sh
          sudo apt-get install \
            texlive-latex-base \
            texlive-fonts-recommended \
            texlive-fonts-extra \
            texlive-latex-extra
          brew install \
            pandoc \
            pandoc-crossref \
            librsvg
```

It's much similar on mac, but `basictex` seems to supply all of the `LaTeX` needs.

**Comment by mxcl** [comment]
@jhheider can you update our README so it is correct for Windows, @artburkart did that work?

**Comment by artburkart** [comment]
I just got back to this. It worked! I've submitted a PR at #51. 👍

**Pull request merged**
