### PR TITLE
Fix: minor improvements to the visualization of the Indonesian pdf 

### PR DESCRIPTION
**Pull request by mfts**
Added two improvements to the PDF:

- mistakenly translated latex command
- missing heading

### CODE REVIEW

**Review by jhheider — APPROVED** [review]
Looks reasonable

**Comment by mxcl** [comment]
I wish we could attach the artifact as a comment or something in the PR, however I tried and failed to do that.

**Comment by jhheider** [comment]
I think it must be possible. After all, the deployment actions modify the PR. I'll add it to my passive consideration list.

**Comment by jhheider** [comment]
This, probably: https://github.com/gavv/pull-request-artifacts

**Pull request merged**
