### PR TITLE
[DE]: translation

### PR DESCRIPTION
**Pull request by MarcosJCarbonell**
- [x] I created a new folder `i18n/[LANG]` for my translated files
- [x] I translated `metadata.yml` file
- [x] I translated `white-paper.md` file

### CODE REVIEW

**Comment by Xercesblu3** [comment]
@mfts can't do this one either

**Comment by jhheider** [comment]
It's running. It's showing failed 16 minutes ago.

**Comment by mfts** [comment]
This one should run and compile properly. Tested it locally. I'm curious if the artifact will show up here, @jhheider  👀

**Comment by jhheider** [comment]
Last run failed due to debian's font installer (no joke). I retriggered, and the artifacts should be in the passing check output, when it finishes. (pushing them back to the PR seems like a heavier lift)

**Comment by jhheider** [comment]
Here, @mfts : https://github.com/teaxyz/white-paper/actions/runs/3108960152

**Comment by mfts** [comment]
> Here, @mfts : https://github.com/teaxyz/white-paper/actions/runs/3108960152

Very cool! 

Ready to merge, @Xercesblu3 💪

**Comment by mfts** [comment]
@Xercesblu3 German translation is ready for merge

**Comment by Xercesblu3** [comment]
Merged!

**Pull request merged**
