### PR TITLE
Add example of typosquatting attack 

### PR DESCRIPTION
**Pull request by mfts**
This PR includes: 
- an example of a typosquatting attack (in section "The Decentralized Registry") 
- source for the example
- incremented all reference numbers accordingly

### CODE REVIEW

**Comment by mxcl** [comment]
Good call, typosquatters would be slashed with the tea registry.

Instead of incrementing all the footnotes, lets use a named footnote, eg. `[^typosquatters]`

**Comment by mfts** [comment]
Great. Will add an update to the PR to address the footnote issue

**Comment by mfts** [comment]
Thanks @mxcl looks correct 👍

**Comment by mxcl** [comment]
https://github.com/teaxyz/white-paper/suites/6863957652/artifacts/265323111

**Pull request merged**
